FROM node:20.9-alpine3.17

# set working directory
WORKDIR /app
# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --force
COPY . ./

EXPOSE 3000
CMD ["npm", "start"]