version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    environment:
      - PORT=3001
      - JWT_PRIVATE_KEY=thisIsARandomPrivateKeyWhichIsGoodForThisProject
      - DATABASE_URL=mysql://root:123456@mysql:3306/projectUni
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
    ports:
      - "3005:3005"
    volumes:
      - ./frontend:/app/frontend

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: