version: '3.8'

services:
  db_project_uni:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_project_uni:/var/lib/mysql
    networks:
      - backend

  backend_project_uni:
    depends_on:
      - db_project_uni
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3001:3001"
    networks:
      - backend
      - frontend

  front_project_uni:
    depends_on:
      - backend_project_uni
    build:
      context: ./frontend
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - "3000:3000"
    networks:
      - frontend
volumes:
  db_project_uni:

networks:
  backend:
  frontend: